version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/chatbot
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_URI:latest .
      - docker push $REPO_URI:latest
artifacts:
  files: '**/*'
